title = "menu".upper()
print(title.center(20, "="))
print("Coffee".ljust(16, ".") + "$7".rjust(4))
print("Muffin".ljust(16, ".") + "$3".rjust(4))
print("Cheesecake".ljust(16, ".") + "$10".rjust(4))
print("BLT Sandwhich".ljust(16, ".") + "$5".rjust(4))
print("Pizza Slice".ljust(16, ".") + "$5".rjust(4))